#!/bin/sh

set -e

# This will log to a file
exec >> "${SNAP_COMMON}/post-refresh-hook.log" 2>&1

# This will log to the system log
logger "Hello, world!"

cat << EOF > /etc/netplan/00-test.yaml
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      nameservers:
        addresses: [8.8.8.8]
EOF

netplan generate

dbus-send --system --type=method_call \
    --print-reply \
    --dest=io.netplan.Netplan \
    /io/netplan/Netplan io.netplan.Netplan.Apply
